# Time, Money, Cashflow, Return, Interest
def simple_return(start_price: float, end_price: float) -> float: ...
def log_return(start_price: float, end_price: float) -> float: ...
def cumulative_return(returns): ...
def annualized_return(total_return: float, periods: int, periods_per_year: int) -> float: ...
def cagr(begin_value: float, end_value: float, years: float) -> float: ...
def normalize_weights(weights):