def present_value(fv: float, rate: float, periods: int) -> float: ...
def future_value(pv: float, rate: float, periods: int) -> float: ...
def discount_factor(rate: float, period: int) -> float: ...
def annuity_present_value(payment: float, rate: float, periods: int) -> float: ...
def perpetuity_value(cashflow: float, rate: float) -> float: ...