# call option payoff, contingent claims
def call_payoff(spot: float, strike: float) -> float: ...
def put_payoff(spot: float, strike: float) -> float: ...
def forward_payoff(spot: float, forward_price: float) -> float: ...