#linear combination, mean-variance, portfolio()
def portfolio_return(weights, expected_returns) -> float: ...
def portfolio_variance(weights, covariance_matrix) -> float: ...
def portfolio_volatility(weights, covariance_matrix) -> float: ...
def rebalance_trades(current_weights, target_weights, portfolio_value: float): ...
def risk_contribution(weights, covariance_matrix): ...