# replication, arbitrage pricing, arrow-debreu pricing, martingale pricing
def price_zero_coupon_bond(face_value: float, yield_rate: float, periods: int) -> float: ...
def price_coupon_bond(face_value: float, coupon_rate: float, yield_rate: float, periods: int, freq: int = 1) -> float: ...
def gordon_growth_value(dividend_next: float, required_return: float, growth: float) -> float: ...
def discounted_cashflow_value(cashflows: list[float], discount_rate: float, terminal_value: float = 0.0) -> float: ...