# Probability measure, Expectation, Expected return
def npv(rate: float, cashflows: list[float]) -> float: ...
def irr(cashflows: list[float], guess: float = 0.1) -> float: ...
def xnpv(rate: float, cashflows, dates) -> float: ...
def xirr(cashflows, dates, guess: float = 0.1) -> float: ...