# volatility, variance, std deviation
def volatility(returns, periods_per_year: int = 252) -> float: ...
def downside_deviation(returns, target: float = 0.0) -> float: ...
def max_drawdown(equity_curve) -> float: ...
def sharpe_ratio(returns, risk_free_rate: float = 0.0, periods_per_year: int = 252) -> float: ...
def sortino_ratio(returns, risk_free_rate: float = 0.0, periods_per_year: int = 252) -> float: ...
def value_at_risk(returns, alpha: float = 0.05) -> float: ...
def conditional_value_at_risk(returns, alpha: float = 0.05) -> float: ...